name: run-scripts

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
      
    - name: Run Multitest Script
      run: |
        cd $GITHUB_WORKSPACE
        bash ./scripts/daynodefree.sh
    - name: Commit
      uses: EndBug/add-and-commit@v4
      with:
        author_name: "GitHub Action"
        author_email: "action@github.com"
        message: "*"
        add: "*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  